import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();
  console.log("user", user);

  if (!user) {
    return null;
  }

  return (
    <div className="flex w-full gap-4 space-x-2 p-4">
      <Image
        src={user.profileImageUrl}
        className="h-10 w-10  rounded-full"
        alt="Profile image"
        width={56}
        height={56}
      />
      <input
        placeholder="Type some emojis :)"
        className="bg-transparent"
      ></input>
    </div>
  );
};

const UserBar = () => {
  const { user } = useUser();

  if (!user) {
    return null;
  }

  return (
    <div className="flex">
      <Image
        src={user.profileImageUrl}
        className="h-16 w-16  rounded-full"
        alt="Profile image"
        width={56}
        height={56}
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div
      key={post.id}
      className="flex items-center gap-4 border-b border-slate-400 p-8"
    >
      <Image
        src={author.profilePicture}
        alt="Author image"
        className="h-12 w-12  rounded-full"
        width={56}
        height={56}
      />
      <div className="flex flex-col">
        <div className="flex gap-2 text-slate-400">
          <span>{`@${author.username}`}</span>
          <span>{`•  ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <div className="flex">{post.content}</div>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) {
    return <div className="flex w-full justify-center p-8">Loading...</div>;
  }

  if (!data) {
    return (
      <div className="flex w-full justify-center p-8">
        Something went wrong...
      </div>
    );
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && (
              <div className="w-full">
                <div className="flex w-full justify-between">
                  <div className="flex items-center  space-x-2">
                    <UserBar />
                    <p>Hi {user.user.fullName}</p>
                  </div>
                  <SignOutButton />
                </div>
                <CreatePostWizard />
              </div>
            )}
          </div>
          <div className="flex flex-col">
            {data.map((fullProps) => (
              <PostView {...fullProps} key={fullProps.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
